on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.INSIGHT_FTP_SERVER }}
        username: ${{ secrets.INSIGHT_FTP_USERNAME}}
        password: ${{ secrets.INSIGHT_FTP_PASSWORD }}
        exclude: |
          config/connect.php